---
driver:
  name: "terraform"
  command_timeout: 2700

provisioner:
  name: "terraform"

verifier:
  name: terraform
  color: false
  fail_fast: false

platforms:
  - name: local

suites:
  - name: "defaults_on_owner_project"
    driver:
      root_module_directory: test/fixtures/defaults_on_owner_project
    verifier:
      systems:
        - name: defaults_on_owner_project
          backend: local
  - name: "defaults_on_editor_project"
    driver:
      root_module_directory: test/fixtures/defaults_on_editor_project
    verifier:
      systems:
        - name: defaults_on_editor_project
          backend: local
