# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# These are post-installation steps that address defects/bugs or are needed after the system has been fully setup

#TODO use kubectl wait command instead of brute force 'sleep'
- name: "Stackdriver patch for bug b/193159157"
  shell: |
    kubectl -n kube-system scale deploy stackdriver-operator --replicas=0
    sleep 5s # wait for stop
    kubectl patch stackdriver stackdriver --type=merge -p '{"spec":{"scalableMonitoring": false}}' -n kube-system
    kubectl -n kube-system scale deploy stackdriver-operator --replicas=1
  environment:
    KUBECONFIG: "{{ kubeconfig_shared_location }}"
  when:
    - (primary_cluster_machine is defined)
    - (primary_cluster_machine == true)
  tags:
  - abm-post-install
  - active-bug-fix

### Add Kube PS1
- name: "Add Kube PS1 to all known users"
  include: add-kube-ps1.yaml
  become: true
  tags:
  - abm-post-install
  - kube-ps1

### Setup CDI cpumanager flag for nodes
- name: "Add CDI required cpumanager label for nodes"
  include: create-cdi-node-label.yaml
  tags:
  - abm-post-install
  - cdi-install
  - cdi-node-hack

### Install Auditd
- name: "Setup Auditd service"
  include: setup-auditd.yaml
  tags:
  - abm-post-install
  - observability-setup

 ### Install Obeservability agents
- name: "Setup Obeservability Agents on Physical"
  include: setup-google-observability.yaml
  when: is_cloud_resource is undefined or is_cloud_resource == False
  tags:
  - abm-post-install
  - observability-setup
