{
 "title": "Control Plane Status",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "label_values(up, cluster)" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(up{cluster=\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "API Servers UP",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{cluster=\"$cluster\",job=\"apiserver\",namespace=~\"$namespace\"} == 1) / sum(up{cluster=\"$cluster\",job=\"apiserver\",namespace=~\"$namespace\"})) * 100"
    }
   ]
  },
  {
   "title": "API Server Version",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(git_version) (kubernetes_build_info{cluster=\"$cluster\",job=\"apiserver\",namespace=~\"$namespace\"})",
     "legendFormat": "{{ git_version }}"
    }
   ]
  },
  {
   "title": "API Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{cluster=\"$cluster\",code!~\"2..\",namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Error Rate"
    },
    {
     "expr": "sum(rate(apiserver_request_total{cluster=\"$cluster\",namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "API Request Latency (95%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apiserver_request_duration_seconds_bucket{cluster=\"$cluster\",namespace=~\"$namespace\",verb!=\"WATCH\"}[5m])) by (le, verb))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Schedulers UP",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{cluster=\"$cluster\",job=\"scheduler\",namespace=~\"$namespace\"} == 1) / sum(up{cluster=\"$cluster\",job=\"scheduler\",namespace=~\"$namespace\"})) * 100"
    }
   ]
  },
  {
   "title": "Scheduler Version",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(git_version) (kubernetes_build_info{cluster=\"$cluster\",job=\"scheduler\",namespace=~\"$namespace\"})",
     "legendFormat": "{{ git_version }}"
    }
   ]
  },
  {
   "title": "Scheduling Attempt Latency (95%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(scheduler_scheduling_attempt_duration_seconds_bucket{cluster=\"$cluster\",namespace=~\"$namespace\"}[5m])) by (le, result))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Number of Unschedulable Pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(plugin) (scheduler_unschedulable_pods{cluster=\"$cluster\",job=\"scheduler\",namespace=~\"$namespace\"})",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  {
   "title": "Controller Mangers UP",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{cluster=\"$cluster\",job=\"controller-manager\",namespace=~\"$namespace\"} == 1) / sum(up{cluster=\"$cluster\",job=\"controller-manager\",namespace=~\"$namespace\"})) * 100"
    }
   ]
  },
  {
   "title": "Controller Manager Version",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(git_version) (kubernetes_build_info{cluster=\"$cluster\",job=\"controller-manager\",namespace=~\"$namespace\"})",
     "legendFormat": "{{ git_version }}"
    }
   ]
  },
  {
   "title": "Running Controllers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (running_managed_controllers{cluster=\"$cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Number of Node Evictions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_collector_evictions_total{cluster=\"$cluster\",namespace=~\"$namespace\"}"
    }
   ]
  }
 ]
}