{
 "title": "Deployment",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_deployment_metadata_generation, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_deployment_metadata_generation{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "deployment",
    "label": "deployment",
    "query": "label_values(kube_deployment_metadata_generation{cluster=\"$cluster\",namespace=\"$namespace\"}, deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Desired Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_deployment_spec_replicas{cluster=\"$cluster\",deployment=\"$deployment\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{cluster=\"$cluster\",deployment=\"$deployment\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_deployment_status_observed_generation{cluster=\"$cluster\",deployment=\"$deployment\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Creation time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(kube_deployment_created{cluster=\"$cluster\",deployment=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Total CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$deployment.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$deployment.*\"})"
    }
   ]
  },
  {
   "title": "Total Network",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$deployment.*\"}[5m])) + sum(rate(container_network_receive_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$deployment.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$deployment.*\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{cluster=\"$cluster\",container!=\"POD\",namespace=\"$namespace\",pod=~\"$deployment.*\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Replicas Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kube_deployment_status_replicas_available{cluster=\"$cluster\",deployment=\"$deployment\",namespace=\"$namespace\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "avg(kube_deployment_status_replicas_unavailable{cluster=\"$cluster\",deployment=\"$deployment\",namespace=\"$namespace\"})",
     "legendFormat": "Unavailable"
    },
    {
     "expr": "avg(kube_deployment_status_replicas_updated{cluster=\"$cluster\",deployment=\"$deployment\",namespace=\"$namespace\"})",
     "legendFormat": "Updated"
    }
   ]
  }
 ]
}