{
 "title": "Node",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(node_boot_time_seconds, cluster)"
   },
   {
    "name": "instance",
    "label": "Machine",
    "query": "label_values(node_boot_time_seconds{cluster=\"$cluster\",job=\"node-exporter\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{cluster=\"$cluster\",instance=\"$instance\"} - node_boot_time_seconds{cluster=\"$cluster\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count by(cpu) (rate(node_cpu_seconds_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])))) - avg(sum by(mode) (rate(node_cpu_seconds_total{cluster=\"$cluster\",instance=\"$instance\",mode=\"idle\"}[5m]))))) / count(count by(cpu) (rate(node_cpu_seconds_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])))"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes{cluster=\"$cluster\",instance=\"$instance\"} / node_memory_MemTotal_bytes{cluster=\"$cluster\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{cluster=\"$cluster\",fstype!=\"rootfs\",instance=\"$instance\",mountpoint=\"/\"} / node_filesystem_size_bytes{cluster=\"$cluster\",fstype!=\"rootfs\",instance=\"$instance\",mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "CPU available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by(cpu) (rate(node_cpu_seconds_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])))"
    }
   ]
  },
  {
   "title": "Memory available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{cluster=\"$cluster\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Disk available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{cluster=\"$cluster\",fstype!=\"rootfs\",instance=\"$instance\",mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_cpu_seconds_total{cluster=\"$cluster\",instance=\"$instance\",mode=\"system\"}[5m]))",
     "legendFormat": "System"
    },
    {
     "expr": "sum by(instance) (rate(node_cpu_seconds_total{cluster=\"$cluster\",instance=\"$instance\",mode=\"user\"}[5m]))",
     "legendFormat": "User"
    },
    {
     "expr": "sum by(instance) (rate(node_cpu_seconds_total{cluster=\"$cluster\",instance=\"$instance\",mode=\"iowait\"}[5m]))",
     "legendFormat": "Iowait"
    },
    {
     "expr": "sum by(mode) (rate(node_cpu_seconds_total{cluster=\"$cluster\",instance=\"$instance\",mode=\"idle\"}[5m]))",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum by(mode) (rate(node_cpu_seconds_total{cluster=\"$cluster\",instance=\"$instance\",mode=\"nice\"}[5m]))",
     "legendFormat": "Nice"
    },
    {
     "expr": "sum by(mode) (rate(node_cpu_seconds_total{cluster=\"$cluster\",instance=\"$instance\",mode=\"irq\"}[5m]))",
     "legendFormat": "Irq"
    },
    {
     "expr": "sum by(mode) (rate(node_cpu_seconds_total{cluster=\"$cluster\",instance=\"$instance\",mode=\"softirq\"}[5m]))",
     "legendFormat": "Softirq"
    },
    {
     "expr": "sum by(mode) (rate(node_cpu_seconds_total{cluster=\"$cluster\",instance=\"$instance\",mode=\"steal\"}[5m]))",
     "legendFormat": "Steal"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{cluster=\"$cluster\",instance=\"$instance\"} - node_memory_MemFree_bytes{cluster=\"$cluster\",instance=\"$instance\"} - node_memory_Buffers_bytes{cluster=\"$cluster\",instance=\"$instance\"} - node_memory_Cached_bytes{cluster=\"$cluster\",instance=\"$instance\"} - node_memory_Slab_bytes{cluster=\"$cluster\",instance=\"$instance\"} - node_memory_PageTables_bytes{cluster=\"$cluster\",instance=\"$instance\"} - node_memory_SwapCached_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
     "legendFormat": "Apps"
    },
    {
     "expr": "node_memory_PageTables_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
     "legendFormat": "Page tables"
    },
    {
     "expr": "node_memory_Slab_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
     "legendFormat": "Slab"
    },
    {
     "expr": "node_memory_Cached_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
     "legendFormat": "Cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_MemFree_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{cluster=\"$cluster\",instance=\"$instance\"} - node_memory_SwapFree_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
     "legendFormat": "Corrupted"
    },
    {
     "expr": "node_memory_SwapCached_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
     "legendFormat": "Swap cache"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
     "legendFormat": "Receive {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
     "legendFormat": "Transmit {{device}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{cluster=\"$cluster\",device!~\"rootfs\",instance=\"$instance\"} - node_filesystem_avail_bytes{cluster=\"$cluster\",device!~\"rootfs\",instance=\"$instance\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Used memory state",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Inactive_file_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "Inactive file"
      },
      {
       "expr": "node_memory_Inactive_anon_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "Inactive anonymous"
      },
      {
       "expr": "node_memory_Active_file_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "Active file"
      },
      {
       "expr": "node_memory_Active_anon_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "Active anonymous"
      }
     ]
    },
    {
     "title": "Memory committed",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Committed_AS_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "Committed AS"
      },
      {
       "expr": "node_memory_CommitLimit_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "Commit Limit"
      }
     ]
    },
    {
     "title": "Memory writeback and dirty",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Writeback_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "Writeback"
      },
      {
       "expr": "node_memory_WritebackTmp_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "Writeback temporary"
      },
      {
       "expr": "node_memory_Dirty_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "Dirty"
      }
     ]
    },
    {
     "title": "Memory shared and Mapped",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Mapped_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "Mapped"
      },
      {
       "expr": "node_memory_Shmem_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "Shared"
      }
     ]
    },
    {
     "title": "Memory slab",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_SUnreclaim_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "Unrelaimable"
      },
      {
       "expr": "node_memory_SReclaimable_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "Relaimable"
      }
     ]
    },
    {
     "title": "Memory Vmalloc",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_VmallocChunk_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "Chunk"
      },
      {
       "expr": "node_memory_VmallocTotal_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_VmallocUsed_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Memory Bounce",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_memory_Bounce_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "Bounce"
      }
     ]
    },
    {
     "title": "Memory Anonymous",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_AnonHugePages_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "Huge pages"
      },
      {
       "expr": "node_memory_AnonPages_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "Pages"
      }
     ]
    },
    {
     "title": "Memory Kernel",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_KernelStack_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "Stack"
      }
     ]
    },
    {
     "title": "Memory Huge pages",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max(node_memory_HugePages_Free{cluster=\"$cluster\",instance=\"$instance\"})",
       "legendFormat": "Free"
      },
      {
       "expr": "max(node_memory_HugePages_Rsvd{cluster=\"$cluster\",instance=\"$instance\"})",
       "legendFormat": "Reserved"
      },
      {
       "expr": "max(node_memory_HugePages_Surp{cluster=\"$cluster\",instance=\"$instance\"})",
       "legendFormat": "Surplus"
      }
     ]
    },
    {
     "title": "Memory direct maping",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_DirectMap1G_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "1GB"
      },
      {
       "expr": "node_memory_DirectMap2M_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "2MB"
      },
      {
       "expr": "node_memory_DirectMap4k_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "4KB"
      }
     ]
    },
    {
     "title": "Memory Unevictable and MLocked",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 78 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Unevictable_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "Unevictable"
      },
      {
       "expr": "node_memory_Mlocked_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "MLocked"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of context switches / interrupts",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_context_switches_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "Context switches"
      },
      {
       "expr": "rate(node_intr_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "Context switches"
      }
     ]
    },
    {
     "title": "Entropy",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "min(node_entropy_available_bits{cluster=\"$cluster\",instance=\"$instance\"})",
       "legendFormat": "Entropy"
      }
     ]
    },
    {
     "title": "Process forking rate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(node_forks_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "Forks"
      }
     ]
    },
    {
     "title": "Processes state",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(node_procs_blocked{cluster=\"$cluster\",instance=\"$instance\"})",
       "legendFormat": "Blocked"
      },
      {
       "expr": "max(node_procs_running{cluster=\"$cluster\",instance=\"$instance\"})",
       "legendFormat": "Running"
      }
     ]
    },
    {
     "title": "Time synchronization drift",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(node_timex_estimated_error_seconds{cluster=\"$cluster\",instance=\"$instance\"})",
       "legendFormat": "Extimated error"
      },
      {
       "expr": "max(node_timex_offset_seconds{cluster=\"$cluster\",instance=\"$instance\"})",
       "legendFormat": "Offset"
      },
      {
       "expr": "max(node_timex_maxerror_seconds{cluster=\"$cluster\",instance=\"$instance\"})",
       "legendFormat": "Maximum error"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk IOps completed",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Reads"
      },
      {
       "expr": "rate(node_disk_writes_completed_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Writes"
      }
     ]
    },
    {
     "title": "Disk R/W data",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Reads"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Writes"
      }
     ]
    },
    {
     "title": "Disk R/W time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_time_seconds_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Reads"
      },
      {
       "expr": "rate(node_disk_write_time_seconds_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Writes"
      }
     ]
    },
    {
     "title": "Disk IO time weighted",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_weighted_seconds_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk R/W merged",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_merged_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Read"
      },
      {
       "expr": "rate(node_disk_writes_merged_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Write"
      }
     ]
    },
    {
     "title": "Disk IO time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Space available",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{cluster=\"$cluster\",device!~\"rootfs\",instance=\"$instance\"}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Free file nodes",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_files_free{cluster=\"$cluster\",device!~\"rootfs\",instance=\"$instance\"}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "File descriptors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(node_filefd_allocated{cluster=\"$cluster\",instance=\"$instance\"})",
       "legendFormat": "Allocated"
      },
      {
       "expr": "min(node_filefd_maximum{cluster=\"$cluster\",instance=\"$instance\"})",
       "legendFormat": "Limit"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network packet traffic",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_packets_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "Receive {{device}} "
      },
      {
       "expr": "rate(node_network_transmit_packets_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "Transmit {{device}}"
      }
     ]
    },
    {
     "title": "Network traffic errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_errs_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "Receive {{device}} "
      },
      {
       "expr": "rate(node_network_transmit_errs_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "Transmit {{device}}"
      }
     ]
    },
    {
     "title": "Network traffic drop",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_drop_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "Receive {{device}} "
      },
      {
       "expr": "rate(node_network_transmit_drop_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "Transmit {{device}}"
      }
     ]
    },
    {
     "title": "Network traffic compressed",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_compressed_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "Receive {{device}} "
      },
      {
       "expr": "rate(node_network_transmit_compressed_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "Transmit {{device}}"
      }
     ]
    },
    {
     "title": "Network traffic multicast",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_multicast_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "Receive {{device}} "
      }
     ]
    },
    {
     "title": "Network traffic fifo",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_fifo_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "Receive {{device}} "
      },
      {
       "expr": "rate(node_network_transmit_fifo_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "Transmit {{device}}"
      }
     ]
    },
    {
     "title": "Network traffic frame",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_frame_total{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "Receive {{device}} "
      }
     ]
    },
    {
     "title": "NF conntrack entries",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_nf_conntrack_entries{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "NF conntrack entries"
      },
      {
       "expr": "node_nf_conntrack_entries_limit{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "NF conntrack limit"
      }
     ]
    }
   ]
  },
  {
   "title": "Sockstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP connection status",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_alloc{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "alloc"
      },
      {
       "expr": "node_sockstat_TCP_inuse{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "inuse"
      },
      {
       "expr": "node_sockstat_TCP_mem{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "mem"
      },
      {
       "expr": "node_sockstat_TCP_orphan{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "orphan"
      },
      {
       "expr": "node_sockstat_TCP_tw{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "tw"
      }
     ]
    },
    {
     "title": "UDP connection status",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_UDPLITE_inuse{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "UDPlite inuse"
      },
      {
       "expr": "node_sockstat_UDP_inuse{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "UDP inuse"
      },
      {
       "expr": "node_sockstat_UDP_mem{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "UDP mem"
      }
     ]
    },
    {
     "title": "Sockets used",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_sockets_used{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Memory used for sockets",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_mem_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "TCP"
      },
      {
       "expr": "node_sockstat_UDP_mem_bytes{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "UDP"
      }
     ]
    },
    {
     "title": "FRAG / RAW sockets state",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_FRAG_inuse{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "FRAG inuse"
      },
      {
       "expr": "node_sockstat_FRAG_memory{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "FRAG memory"
      },
      {
       "expr": "node_sockstat_RAW_inuse{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "RAW inuse"
      }
     ]
    }
   ]
  },
  {
   "title": "Netstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP segments rate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_InCsumErrors{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "Checksum errors"
      },
      {
       "expr": "rate(node_netstat_Tcp_InErrs{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "Error"
      },
      {
       "expr": "rate(node_netstat_Tcp_InSegs{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "Received"
      },
      {
       "expr": "rate(node_netstat_Tcp_OutRsts{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "Sent with RST"
      },
      {
       "expr": "rate(node_netstat_Tcp_OutSegs{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "Sent"
      },
      {
       "expr": "rate(node_netstat_Tcp_RetransSegs{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "Retransmitted"
      }
     ]
    },
    {
     "title": "TCP connections",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "Established"
      },
      {
       "expr": "node_netstat_Tcp_MaxConn{cluster=\"$cluster\",instance=\"$instance\"}",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "TCP Direct Transition",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_ActiveOpens{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "ActiveOpen"
      },
      {
       "expr": "rate(node_netstat_Tcp_AttemptFails{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "AttemptFails"
      },
      {
       "expr": "rate(node_netstat_Tcp_EstabResets{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "EstabResets"
      },
      {
       "expr": "rate(node_netstat_Tcp_PassiveOpens{cluster=\"$cluster\",instance=\"$instance\"}[5m])",
       "legendFormat": "PassiveOpens"
      }
     ]
    }
   ]
  }
 ]
}