{
 "title": "Resource Usage by Pod",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kubernetes_io:anthos_container_uptime, cluster_name)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kubernetes_io:anthos_container_uptime{cluster_name=\"$cluster\"}, namespace_name)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kubernetes_io:anthos_container_uptime{cluster_name=\"$cluster\",namespace_name=\"$namespace\"}, pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name) (rate(kubernetes_io:anthos_container_cpu_core_usage_time{cluster_name=\"$cluster\",namespace_name=~\"$namespace\",pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "CPU Request",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name) (kubernetes_io:anthos_container_cpu_request_cores{cluster_name=\"$cluster\",namespace_name=~\"$namespace\",pod_name=~\"$pod\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "CPU Limit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name) (kubernetes_io:anthos_container_cpu_limit_cores{cluster_name=\"$cluster\",namespace_name=~\"$namespace\",pod_name=~\"$pod\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name) (kubernetes_io:anthos_container_memory_used_bytes{cluster_name=\"$cluster\",namespace_name=~\"$namespace\",pod_name=~\"$pod\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name) (kubernetes_io:anthos_container_memory_request_bytes{cluster_name=\"$cluster\",namespace_name=~\"$namespace\",pod_name=~\"$pod\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name) (kubernetes_io:anthos_container_memory_limit_bytes{cluster_name=\"$cluster\",namespace_name=~\"$namespace\",pod_name=~\"$pod\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by (interface) (rate(kubernetes_io:anthos_pod_network_received_bytes_count{cluster_name=\"$cluster\",namespace_name=~\"$namespace\",pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by (interface) (rate(kubernetes_io:anthos_pod_network_sent_bytes_count{cluster_name=\"$cluster\",namespace_name=~\"$namespace\",pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "{{interface}}"
    }
   ]
  }
 ]
}