apiVersion: demo.anthos.com/v1
kind: CompositeCluster 
metadata:
  name: a-team
  labels:
    cluster-owner: prod-cluster
spec:
  compositionRef:
    # Possible values cluster-gcp, cluster-azure, cluster-aws
    name: cluster-aws
  parameters:
    # Possible values small, medium, large
    nodeSize: medium
    k8sVersion: "1.23"
    fleetProject: "261832825633"
    minNodeCount: 3  
    adminUsers:
    - bkauf@google.com
  writeConnectionSecretToRef:
    namespace: default
    name: a-team