# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## Vars specifically for CNUC1

# Name of the cluster
cluster_name: "cnuc-1"
# Used for logging/metrics
machine_label: "cnuc-1"
# Indicates that this is the primary machine in the cluster (only important for provisioning)
primary_cluster_machine: true
# Name of the "store" per the ACM repo
acm_cluster_name: "{{ lookup('env', 'CLUSTER_ACM_NAME') | default('location-2', True) }}"
# This machine's IP
control_plane_ip: "10.200.0.2"
# The other IPs in the cluster
control_plane_ips: [
  "10.200.0.2",
  "10.200.0.3",
  "10.200.0.4"
]
# KubeAPI IP address
control_plane_vip: "10.200.0.49"
# Ingress (k8s) address, must be in LoadBalancer pool below
ingress_vip: "10.200.0.50"
# Load balancers created in this range
load_balancer_pool_cidr: [
  "10.200.0.50-10.200.0.70"
]

# Ansible Pull Authenticaiton String
ansible_pull_authentication_string: "{{scm_token_user}}:{{scm_token_token}}@"

# Ansible Pull repo for Remote Execution
ansible_pull_remote_execute_repo: "https://{{ ansible_pull_authentication_string | default('', true) }}gitlab.com/gcp-solutions-public/retail-edge/remote-command-repo.git"

# Ansible pull repo to manage simplified drift
ansible_pull_drift_repo: "https://{{ ansible_pull_authentication_string | default('', true) }}gitlab.com/gcp-solutions-public/retail-edge/drift-repo.git"
