apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default-aws
spec:
  credentials:
    secretRef:
      key: creds
      name: aws-creds
      namespace: crossplane-system
    source: Secret